version: "2.2"
services:
  martin-redis:
    image: redis:4.0.10
    restart: on-failure
    mem_limit: 256m
    container_name: martin-redis
    ports:
      - 6379:6379
    networks:
      - martin

  martin-extension-monitor:
    build:
      context: ./
      dockerfile: ./martin-extension/martin-extension-monitor/Dockerfile
    restart: on-failure
    mem_limit: 256m
    container_name: martin-extension-monitor
    image: martin-extension-monitor
    environment:
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: "martin-skywalking-oap:11800"
      JAVA_OPTS: " -Xms256m -Xmx256m -javaagent:/opt/agent/skywalking-agent.jar -Dskywalking.agent.service_name=MartinExtensionMonitor"
    volumes:
      - ./logs:/martin-extension-monitor/logs
    ports:
      - 9601:9601
    networks:
      - martin

  martin-cloud-gateway:
    build:
      context: ./
      dockerfile: ./martin-cloud/martin-cloud-gateway/Dockerfile
    restart: on-failure
    mem_limit: 256m
    container_name: martin-cloud-gateway
    image: martin-cloud-gateway
    environment:
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: "martin-skywalking-oap:11800"
      JAVA_OPTS: " -Xms256m -Xmx256m -javaagent:/opt/agent/skywalking-agent.jar -Dskywalking.agent.service_name=MartinCloudGateway"
    volumes:
      - ./logs:/martin-cloud-gateway/logs
    ports:
      - 9502:9502
    networks:
      - martin


  martin-biz-auth:
    build:
      context: ./
      dockerfile: ./martin-biz/martin-biz-auth/Dockerfile
    restart: on-failure
    mem_limit: 256m
    container_name: martin-biz-auth
    image: martin-biz-auth
    environment:
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: "martin-skywalking-oap:11800"
      JAVA_OPTS: " -Xms256m -Xmx256m -javaagent:/opt/agent/skywalking-agent.jar -Dskywalking.agent.service_name=MartinBizAuth"

    volumes:
      - ./logs:/martin-biz-auth/logs
    networks:
      - martin


  martin-biz-resource:
    build:
      context: ./
      dockerfile: ./martin-biz/martin-biz-resource/Dockerfile
    restart: on-failure
    mem_limit: 256m
    container_name: martin-biz-resource
    image: martin-biz-resource
    environment:
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: "martin-skywalking-oap:11800"
      JAVA_OPTS: " -Xms256m -Xmx256m -javaagent:/opt/agent/skywalking-agent.jar -Dskywalking.agent.service_name=MartinBizResource"
    volumes:
      - ./logs:/martin-biz-resource/logs
    networks:
      - martin


  martin-biz-swagger:
    build:
      context: ./
      dockerfile: ./martin-biz/martin-biz-swagger/Dockerfile
    restart: on-failure
    mem_limit: 256m
    container_name: martin-biz-swagger
    image: martin-biz-swagger
    environment:
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: "martin-skywalking-oap:11800"
      JAVA_OPTS: " -Xms256m -Xmx256m -javaagent:/opt/agent/skywalking-agent.jar -Dskywalking.agent.service_name=MartinBizSwagger"
    volumes:
      - ./logs:/martin-biz-swagger/logs
    networks:
      - martin

  martin-biz-system:
    build:
      context: ./
      dockerfile: ./martin-biz/martin-biz-system/Dockerfile
    restart: on-failure
    mem_limit: 256m
    container_name: martin-biz-system
    image: martin-biz-system
    environment:
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: "martin-skywalking-oap:11800"
      JAVA_OPTS: " -Xms256m -Xmx256m -javaagent:/opt/agent/skywalking-agent.jar -Dskywalking.agent.service_name=MartinBizSystem"
    volumes:
      - ./logs:/martin-biz-system/logs
    networks:
      - martin

  martin-ui:
    build:
      context: ./
      dockerfile: ./ui/Dockerfile
    restart: on-failure
    mem_limit: 256m
    container_name: martin-ui
    image: martin-ui
    ports:
      - 8000:80
    volumes:
      - ./logs/nginx:/var/log/nginx
    networks:
      - martin

networks:
  martin:
    external: true
