# 使用说明 V0.0.1
# 1. 使用docker-compose  宿主机不需要配置host来发现
# 2. 无需修改源码，根目录  docker-compose up 即可
# 3. 静静等待服务启动

version: '2'
services:
  martin-mysql:
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: martin-mysql
    image: martin-mysql
    ports:
      - 3306:3306

  martin-zookeeper:
    image: zookeeper:3.4.13
    restart: always

  martin-redis:
    image: redis:4.0.10
    restart: always
    container_name: martin-redis

  martin-cloud-eureka:
    build:
      context: ./
      dockerfile: ./martin-cloud/martin-cloud-eureka/Dockerfile
    restart: always
    container_name: martin-cloud-eureka
    image: martin-cloud-eureka
    ports:
      - 9500:9500

  martin-cloud-config:
    build:
      context: ./
      dockerfile: ./martin-cloud/martin-cloud-config/Dockerfile
    restart: always
    container_name: martin-cloud-config
    image: martin-cloud-config
    depends_on:
      - martin-cloud-eureka
    entrypoint: "wait-for-it.sh -t 10 martin-cloud-eureka:9500 -- "

  martin-cloud-gateway:
    build:
      context: ./
      dockerfile: ./martin-cloud/martin-cloud-gateway/Dockerfile
    restart: always
    container_name: martin-cloud-gateway
    image: martin-cloud-gateway
    depends_on:
      - martin-cloud-eureka
      - martin-cloud-config
    entrypoint: "wait-for-it.sh -t 10 martin-cloud-config:9501 -- "
    ports:
      - 9527:9527

