# V0.0.1

version: '2'
services:
#  martin-mysql:
#    build:
#      context: ./
#      dockerfile: ./db/Dockerfile
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    restart: always
#    privileged: true
#    container_name: martin-mysql
#    image: martin-mysql
#    volumes:
#      - /opt/docker/mysql:/var/lib/mysql
#    ports:
#      - 3306:3306
#
#  martin-zookeeper:
#    image: zookeeper:3.4.13
#    restart: always
#
#  martin-redis:
#    image: redis:4.0.10
#    restart: always
#    container_name: martin-redis

  martin-cloud-eureka:
    build:
      context: ./
      dockerfile: ./martin-cloud/martin-cloud-eureka/Dockerfile
    restart: always
    container_name: martin-cloud-eureka
    image: martin-cloud-eureka
    volumes:
      - ./logs:/martin-cloud-eureka/logs
    ports:
      - 9000:9000

  martin-cloud-config:
    build:
      context: ./
      dockerfile: ./martin-cloud/martin-cloud-config/Dockerfile
    restart: always
    container_name: martin-cloud-config
    image: martin-cloud-config
    volumes:
      - ./logs:/martin-cloud-config/logs
    depends_on:
      - martin-cloud-eureka
    entrypoint: "wait-for-it.sh -t 0 martin-cloud-eureka:9000 -- "
    command: "java -Djava.security.egd=file:/dev/./urandom -jar -Xms128m -Xmx256m -XX:PermSize=128m -XX:MaxPermSize=256m martin-cloud-config.jar"
    ports:
      - 9100:9100

  martin-cloud-gateway:
    build:
      context: ./
      dockerfile: ./martin-cloud/martin-cloud-gateway/Dockerfile
    restart: always
    container_name: martin-cloud-gateway
    image: martin-cloud-gateway
    volumes:
      - ./logs:/martin-cloud-gateway/logs
    depends_on:
      - martin-cloud-eureka
      - martin-cloud-config
    entrypoint: "wait-for-it.sh -t 0 martin-cloud-config:9100 -- "
    command: "java -Djava.security.egd=file:/dev/./urandom -jar -Xms128m -Xmx256m -XX:PermSize=128m -XX:MaxPermSize=256m martin-cloud-gateway.jar"
    ports:
      - 9527:9527


  martin-biz-auth:
    build:
      context: ./
      dockerfile: ./martin-biz/martin-biz-auth/Dockerfile
    restart: always
    container_name: martin-biz-auth
    image: martin-biz-auth
    volumes:
      - ./logs:/martin-biz-auth/logs
    depends_on:
      - martin-cloud-eureka
      - martin-cloud-config
    entrypoint: "wait-for-it.sh -t 0 martin-cloud-config:9100 -- "
    command: "java -Djava.security.egd=file:/dev/./urandom -jar -Xms128m -Xmx256m -XX:PermSize=128m -XX:MaxPermSize=256m martin-biz-auth.jar"

  martin-biz-auth-resource:
    build:
      context: ./
      dockerfile: ./martin-biz/martin-biz-auth-resource/Dockerfile
    restart: always
    container_name: martin-biz-auth-resource
    image: martin-biz-auth-resource
    volumes:
      - ./logs:/martin-biz-auth-resource/logs
    depends_on:
      - martin-cloud-eureka
      - martin-cloud-config
    entrypoint: "wait-for-it.sh -t 0 martin-cloud-config:9100 -- "
    command: "java -Djava.security.egd=file:/dev/./urandom -jar -Xms128m -Xmx256m -XX:PermSize=128m -XX:MaxPermSize=256m martin-biz-auth-resource.jar"

  martin-biz-auth-sso:
    build:
      context: ./
      dockerfile: ./martin-biz/martin-biz-auth-sso/Dockerfile
    restart: always
    container_name: martin-biz-auth-sso
    image: martin-biz-auth-sso
    volumes:
      - ./logs:/martin-biz-auth-sso/logs
    depends_on:
      - martin-cloud-eureka
      - martin-cloud-config
    entrypoint: "wait-for-it.sh -t 0 martin-cloud-config:9100 -- "
    command: "java -Djava.security.egd=file:/dev/./urandom -jar -Xms128m -Xmx256m -XX:PermSize=128m -XX:MaxPermSize=256m martin-biz-auth-sso.jar"

