spring:
  profiles:
    active: dev

foot: foot

auth-server: http://localhost:9400

#本项目用一个资源配置，将来可为每个服务单独配置oauth信息
security:
  oauth2:
    client:
      client-id: client2 # 授权服务器配置的client id
      client-secret: 123456 # 授权服务器配置的client secret
      scope: all
      #access-token-uri: ${auth-server}/oauth/token # 获取access token接口
      #user-authorization-uri: ${auth-server}/oauth/authorize #  获取Authorization Code接口
    resource:
      token-info-uri: ${auth-server}/oauth/check_token # 验证token的接口
#      user-info-uri: ${auth-server}/user # 一个可以获取认证授权的自定义接口，可以在授权服务器，也可以在其他服务器上
#      prefer-token-info: true # 如果同时配置了token-info-uri 和 user-info-uri，这个现象设置使用哪个取验证授权

#swagger公共信息
swagger:
  host: localhost:9502
  title: Amap Swagger API
  description: Martin 聚合文档
  version: 2.0
  license: Powered By java2e
  licenseUrl: http://java2e.com/
  terms-of-service-url: http://java2e.com/
  contact:
    name: 梁灿
    email: liangcan.jxjy.edu@gmail.com
    url: https://java2e.com/about.html
  authorization:
    name: Martin OAuth
    auth-regex: ^.*$
    authorization-scope-list:
      - scope: server
        description: server all
    token-url-list:
      - ${security.auth.server}/token

martin:
  swagger:
    enabled: true
  resource-server:
    enabled: true
  feign:
    enabled: true