spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: martin-biz-hello
          uri: lb://martin-biz-hello
          predicates:
            - Path=/hello/**
          filters:
            - StripPrefix=1