spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: martin-biz-hello
          uri: lb://martin-biz-hello
          predicates:
            - Path=/hello/**
          filters:
            - StripPrefix=1
        - id: martin-biz-auth
          uri: lb://martin-biz-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: martin-biz-auth-resource
          uri: lb://martin-biz-auth-resource
          predicates:
            - Path=/resource/**
          filters:
            - StripPrefix=1
        - id: martin-biz-auth-sso
          uri: lb://martin-biz-auth-sso
          predicates:
            - Path=/sso/**
          filters:
            - StripPrefix=1