spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: martin-biz-auth
          uri: lb://martin-biz-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: martin-biz-resource
          uri: lb://martin-biz-resource
          predicates:
            - Path=/resource/**
          filters:
            - StripPrefix=1
        - id: martin-biz-sso
          uri: lb://martin-biz-sso
          predicates:
            - Path=/sso/**
          filters:
            - StripPrefix=1
        - id: martin-biz-swagger
          uri: lb://martin-biz-swagger
          predicates:
            - Path=/swagger/**
          filters:
            - StripPrefix=1
        - id: martin-biz-system
          uri: lb://martin-biz-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1