security:
  oauth2:
    client:
      client-id: client3
      client-secret: 123456
      scope: sso
      ignore-urls:
        - /client/test
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
