import React from "react";

export default[
    {
      title: '用户名',
      dataIndex: 'username',
      key: 'username',
      width: 150,
    },
    {
      title: '密码',
      dataIndex: 'pwd',
      key: 'pwd',
      width: 150,
    },
    {
      title: '随机盐',
      dataIndex: 'salt',
      key: 'salt',
      width: 150,
    },
    {
      title: '年纪',
      dataIndex: 'age',
      key: 'age',
      width: 150,
    },
    {
      title: '头像',
      dataIndex: 'avatar',
      key: 'avatar',
      width: 150,
    },
    {
      title: '邮箱',
      dataIndex: 'email',
      key: 'email',
      width: 150,
    },
    {
      title: '签名',
      dataIndex: 'signature',
      key: 'signature',
      width: 150,
    },
    {
      title: '头衔',
      dataIndex: 'title',
      key: 'title',
      width: 150,
    },
    {
      title: '分类',
      dataIndex: 'classification',
      key: 'classification',
      width: 150,
    },
    {
      title: '地址',
      dataIndex: 'address',
      key: 'address',
      width: 150,
    },
    {
      title: '电话',
      dataIndex: 'phone',
      key: 'phone',
      width: 150,
    },
    {
      title: '部门ID',
      dataIndex: 'deptId',
      key: 'deptId',
      width: 150,
    },
    {
      title: '微信openid',
      dataIndex: 'wxOpenid',
      key: 'wxOpenid',
      width: 150,
    },
    {
      title: 'QQ openid',
      dataIndex: 'qqOpenid',
      key: 'qqOpenid',
      width: 150,
    },
    {
      title: '所属租户',
      dataIndex: 'tenantId',
      key: 'tenantId',
      width: 150,
    },
    {
      title: '0-正常，9-锁定',
      dataIndex: 'lockFlag',
      key: 'lockFlag',
      width: 150,
    },
    {
      title: '删除标识（0-正常,1-删除）',
      dataIndex: 'delFlag',
      key: 'delFlag',
      width: 150,
    },
    {
      title: '创建时间',
      dataIndex: 'createTime',
      key: 'createTime',
      width: 150,
    },
    {
      title: '修改时间',
      dataIndex: 'updateTime',
      key: 'updateTime',
      width: 150,
    },
    {
      title: '创建人',
      dataIndex: 'creator',
      key: 'creator',
      width: 150,
    },
    {
      title: '修改人',
      dataIndex: 'updater',
      key: 'updater',
      width: 150,
    },
]